### PR TITLE
Implement rendering of parse error context

### LINKED ISSUE #205: Implement optional displaying of releavant region of input in error messages
For version 6, I want to have something like this:

```
my-file.txt:8:6:

x = 1a
     ^

unexpected 'a'
expecting newline or the rest of integer
```

Regarding implementation, I think we are not going to store input regions for this, so no changes to the parsing process should be necessary (as we don't want to make things slower, in fact version 6 is about making things faster). The most obvious thing (and robust) is to traverse original input updating position till we find the position from `ParseError`. Remembering where the most recent line begins will allow us to extract just the relevant line of input and display it.

I'm not sure how to do it better without making the feature fragile. It seems that we can't use total number of processed tokens to figure out where `ParseError` happened, because in some cases, for example when using `region` to overwrite error position, total number of processed tokens would be out-of-sync.

This feature should be optional.

### PR DESCRIPTION
**Pull request by mrkkrp**
Resolves #205, continuation of #233.

### CODE REVIEW

**Comment by mrkkrp** [comment]
@recursion-ninja, This is a simpler version without the setting that controls max line width. My logic was that lines as long as several thousand characters are not common, and we'll be able to add more functionality in backward-compatible way in 6.x.x series of the library. Let's start with basic line rendering for now.

**Comment by recursion-ninja** [comment]
I saw that. I know that the bio-informatics program I'm working on often accepts files with *very* long lines, but I'm not sure how common that is in general.

I wish I had more time to get the more general rendering working. I'll keep poking around with the more general approach. Hopefully, I can do that without the problematic "total tokens consumed" field.

**Comment by recursion-ninja** [comment]
It just dawned on me, that I could just use my version of `parseErrorPrettyWithContex` defined outside of the `megaparsec` library on the 1000+ line length bio-informatics files. 

Do you think there is value in trying to include this kind of error rendering in a later release, or should I just have a custom renderer for my program?

**Comment by mrkkrp** [comment]
I'm honestly not sure how common this use case is. I think it's best for you to use your custom solution. See how things are done in the released version of library, perhaps you could adjust `parseErrorPrettyWithContext` to use `LineToken` type class, etc. Then we can try to include it in the library.

**Pull request merged**
