### PR TITLE
Adapt to MonadFail changes in base 4.13.

### PR DESCRIPTION
**Pull request by AndreasPK**

### CODE REVIEW

**Comment by AndreasPK** [comment]
Tested it with 8.6.4 and HEAD.

**Comment by mrkkrp** [comment]
Can you please add a bit of background for this change? @hvr could you take a look?

**Comment by mrkkrp** [comment]
AFAIU `fail` will be finally dropped from `Monad` in the next GHC release?

**Comment by AndreasPK** [comment]
> AFAIU `fail` will be finally dropped from `Monad` in the next GHC release?

That is correct. See eg the entry on haskell wiki. https://wiki.haskell.org/MonadFail_Proposal

**Comment by mrkkrp** [comment]
Sounds good, I merged this in.

**Pull request merged**
