### PR TITLE
add integerBase

### PR DESCRIPTION
**Pull request by minad**
See https://github.com/mrkkrp/megaparsec/issues/101

This still needs tests and the char functions should probably go to Megaparsec.Char.

Is this generally ok?

### CODE REVIEW

**Comment by mrkkrp** [comment]
Thanks. Here are some points:

* Just ignoring a character (for example `,` in `1,000,000`) is not good enough. When characters delimiters are used, they are used in a meaningful way, so we should parse them in a meaningful way as well. I.e. accepting something like `,,,,0` along with `1,000,000` is not OK.

* I think we should not combine the feature to support `1_000_000` and `1,000,000` things with parser for numbers in given base. The two features seem to be completely independent and never used together. How often would anyone want to parse a number in base 20 and delimit characters with `,` at the same time?

* If we start to mess with “delimiting characters”, the feature should work not only for integers, e.g. this is a valid use case: `1,000.00`.

* Please be careful not to break existing formatting as on lines 192-194, or I'll need to cherry-pick/amend your commits to fix it back — not fun!

* I think the character parsing functions should **not** go to `Text.Megaprasec.Char`, as their use outside of `integerBase` seems to be non-existent.

* Could something like [this](https://hackage.haskell.org/package/base-4.9.1.0/docs/Numeric.html#v:readInt) be used instead of manual calculations? Also, please don't covert existing code unless we previously explicitly agreed that it's OK.

(Note to self: these `readDec`, `readOct`, and `readHex` friends could actually be better than prefixing numbers and feeding them into `read`.)

OK, sorry for making so many remarks! I appreciate you're working on this, I just need to keep things in good shape :-) Bottom line: I think it's best to concentrate just on a parser that parses numbers in arbitrary base for now.

**Comment by minad** [comment]
1. The ignore parser does exactly that. It requires the ignored character to be preceded and followed by a digit.
2. How then? integerBase should just function as a generalized integer parser with generalized base and ignored delimiters.
3. Yes, we could also provide such a thing for floats.
4. Typo.
5. Ok with me.
6. I've seen this function, but it seemed to be too involved due to the additional isDigit checking. However now that I looked again, it seems readInt uses a optimized internal parser, which would make it useful (See https://hackage.haskell.org/package/base-4.9.1.0/docs/src/Text.Read.Lex.html#valInteger). I strongly disagree with the way you handle the parsing now using "0x" prefixing. Therefore I changed it.

I appreciate that you want to keep things in good shape.

**Comment by minad** [comment]
Maybe I should add my use case: Assume I want to parse numbers of the format 2'1000_0111_0000, 10'123_456_789 etc

How could I do that using the given infrastructure. This PR tries to provide the necessary combinator.

**Comment by mrkkrp** [comment]
I don't see how to add the feature with delimiter characters nicely without breaking compatibility, perhaps it is a bit too specific, I'm not sure. I don't like the prefixing technique too (although it's totally safe in our case), I should find time to benchmark the parsers to find out if switching to `readDec` and friends can improve the situation. These reader functions may perform better than gerenal `read` we use right now.

If you build `integerBase` on top of `readInt` from `Numeric`, we can merge that. If you do, don't forget to add `@since 5.2.0` note, changelog note, and tests.

**Comment by minad** [comment]
What is the problem with backward compatibility? decimal, hexadecimal etc could stay as they are.
If you don't want to add the ignore feature, it is also ok for me.

**Comment by mrkkrp** [comment]
Because ideally this should be an argument for already existing parsers that produce integers, floats, scientific. We don't want to add a bunch of mostly identical combinators, it would be ugly, but at the same time we can't add new arguments to existing parsers because it would break backward compatibility.

**Comment by minad** [comment]
Ok, probably it is too much and would be used only seldom.

**Comment by mrkkrp** [comment]
Are you interested in `integerBase` parser without ignoring characters?

**Comment by mrkkrp** [comment]
I want to replace implementation of `decimal` and friends, I could add `integerBase` as well. Or is it only of interested when combined for the "ignorable characters" feature?

**Comment by minad** [comment]
I need the ignore feature. This is somehow all or nothing since if megaparsec doesn't support it directly I have to use my own combinator and could not reuse integerBase. But I am unsure if this feature is out of scope for megaparsec. It doesn't make much sense to add weird parsers which are never used.

**Pull request closed without merging**
